let localizers = {
  
  'zh-CN': {
      "Introduction": "Introduction",
      "Hello.": "Hello.",
      "I am an interactive |Vim| tutorial.": "I am an interactive |Vim| tutorial.",
      "I'll teach you what Vim is about without hassle. If you are in a hurry, press any key to fast forward.": "I'll teach you what Vim is about without hassle. If you are in a hurry, press any key to fast forward.",
      "To practice what you've learned, try out the |practice| page. It has a context sensitive reference for commands.": "To practice what you've learned, try out the |practice| page. It has a context sensitive reference for commands.",
      "Now, let me introduce you to basics of Vim.": "Now, let me introduce you to basics of Vim.",
      "Two modes, insert and normal": "Two modes, insert and normal",
      "Vim has two basic modes. One is |insert| mode, in which you write text as if in normal text editor.": "Vim has two basic modes. One is |insert| mode, in which you write text as if in normal text editor.",
      "Another is |normal| mode which provides you efficient ways to navigate and manipulate text.": "Another is |normal| mode which provides you efficient ways to navigate and manipulate text.",
      "At any time, you can see which mode you are in on the status bar which is located at the top of the editor.": "At any time, you can see which mode you are in on the status bar which is located at the top of the editor.",
      "To change between modes, use |Esc| for normal mode and |i| for insert mode": "To change between modes, use |Esc| for normal mode and |i| for insert mode",
      "Let's try it out! First, change to insert mode.": "Let's try it out! First, change to insert mode.",
      "Basic movement: h, j, k, and l": "Basic movement: h, j, k, and l",
      "In contrast to regular text editor, you use keys |h|, |j|, |k|, and |l| instead of arrow keys to move the cursor.": "In contrast to regular text editor, you use keys |h|, |j|, |k|, and |l| instead of arrow keys to move the cursor.",
      "Let's see how it works in practice!": "Let's see how it works in practice!",
      "Word movement: w, e, b": "Word movement: w, e, b",
      "To navigate the text in terms of words, you can use keys |w|, |b|, and |e| (also W, B, E in real Vim).": "To navigate the text in terms of words, you can use keys |w|, |b|, and |e| (also W, B, E in real Vim).",
      "|w| moves to the start of next word; |e| moves to the end of the word; and |b| moves to beginning of the word.": "|w| moves to the start of next word; |e| moves to the end of the word; and |b| moves to beginning of the word.",
      "Number powered movement, e.g. 5w": "Number powered movement, e.g. 5w",
      "Moving within the text is not limited to individual keys; you can combine movement keys with a |number|. For example, |3w| is the same as pressing w three times.": "Moving within the text is not limited to individual keys; you can combine movement keys with a |number|. For example, |3w| is the same as pressing w three times.",
      "Insert text repeatedly, e.g. 3iYes": "Insert text repeatedly, e.g. 3iYes",
      "You can insert text multiple times.": "You can insert text multiple times.",
      "For example, an underline of a header might consist of 30 |-|s.": "For example, an underline of a header might consist of 30 |-|s.",
      "------------------------------": "------------------------------",
      "With |30i-| |Esc|, there's no need to press |-| 30 times.": "With |30i-| |Esc|, there's no need to press |-| 30 times.",
      "Let's try it out: insert |go| three times.": "Let's try it out: insert |go| three times.",
      "Find a character, f and F": "Find a character, f and F",
      "To find and move to the next (or previous) occurrence of a character, use |f| and |F|, e.g. |fo| finds next o.": "To find and move to the next (or previous) occurrence of a character, use |f| and |F|, e.g. |fo| finds next o.",
      "You can combine f with a number. For example, you can find 3rd occurrence of 'q' with |3fq|, que?": "You can combine f with a number. For example, you can find 3rd occurrence of 'q' with |3fq|, que?",
      "Go to matching parentheses, %": "Go to matching parentheses, %",
      "In text that is structured with parentheses or brackets, |(| or |{| or |[|, use |%| to jump to the matching parenthesis or bracket.": "In text that is structured with parentheses or brackets, |(| or |{| or |[|, use |%| to jump to the matching parenthesis or bracket.",
      "Here is (a sample) text to try that.": "Here is (a sample) text to try that.",
      "Go to start/end of line, 0 and $": "Go to start/end of line, 0 and $",
      "To reach the beginning of a line, press |0|.": "To reach the beginning of a line, press |0|.",
      "For the end of a line, there's |$|": "For the end of a line, there's |$|",
      "Find word under cursor, * and #": "Find word under cursor, * and #",
      "Find the next occurrence of the word under cursor with |*|, and the previous with |#|.": "Find the next occurrence of the word under cursor with |*|, and the previous with |#|.",
      "Goto line, g and G": "Goto line, g and G",
      "|gg| takes you to the beginning of the file; |G| to the end.": "|gg| takes you to the beginning of the file; |G| to the end.",
      "To jump directly to a specific line, give its |line number| along with |G|.": "To jump directly to a specific line, give its |line number| along with |G|.",
      "Now go to the beginning of this screen with |gg| and then back to end with |G|.": "Now go to the beginning of this screen with |gg| and then back to end with |G|.",
      "Search, /text with n and N": "Search, /text with n and N",
      "Searching text is a vital part of any text editor. In Vim, you press |/|, and give the text you are looking for.": "Searching text is a vital part of any text editor. In Vim, you press |/|, and give the text you are looking for.",
      "You can repeat the search for next and previous occurrences with |n| and |N|, respectively.": "You can repeat the search for next and previous occurrences with |n| and |N|, respectively.",
      "For advanced use cases, it's possible to use regexps that help to find text of particular form (In real Vim).": "For advanced use cases, it's possible to use regexps that help to find text of particular form (In real Vim).",
      "Let's try a simple text search.": "Let's try a simple text search.",
      "Search for |text| and find the subsequent matches with |n|.": "Search for |text| and find the subsequent matches with |n|.",
      "Removing a character, x and X": "Removing a character, x and X",
      "|x| and |X| delete the character under the cursor and to the left of the cursor, respectively": "|x| and |X| delete the character under the cursor and to the left of the cursor, respectively",
      "Try pressing |x| to remove the last word.": "Try pressing |x| to remove the last word.",
      "Replacing letter under cursor, r": "Replacing letter under cursor, r",
      "When you need to replace only one character under your cursor, without changing to insert mode, use |r|.": "When you need to replace only one character under your cursor, without changing to insert mode, use |r|.",
      "Replace my": "Replace my",
      "Insert new line, o and O": "Insert new line, o and O",
      "To insert text into a new line, press |o| or |O|": "To insert text into a new line, press |o| or |O|",
      "After new line is created, the editor is set to |insert| mode.": "After new line is created, the editor is set to |insert| mode.",
      "Write a bit and get back to |normal| mode.": "Write a bit and get back to |normal| mode.",
      "Deleting, d": "Deleting, d",
      "|d| is the delete command": "|d| is the delete command",
      "You can combine it with movement, e.g. |dw| deletes the first word on the right side of the cursor": "You can combine it with movement, e.g. |dw| deletes the first word on the right side of the cursor",
      "It also copies the content, so that you can paste it with |p| to another location (on real Vim).": "It also copies the content, so that you can paste it with |p| to another location (on real Vim).",
      "Repetition with .": "Repetition with .",
      "To repeat the previous command, just press |.|": "To repeat the previous command, just press |.|",
      "First, remove two words with |d2w|.": "First, remove two words with |d2w|.",
      "After that, remove the rest of the words in this line with |.|": "After that, remove the rest of the words in this line with |.|",
      "Visual mode, v": "Visual mode, v",
      "Besides insert and normal mode, Vim has also |visual| mode.": "Besides insert and normal mode, Vim has also |visual| mode.",
      "In visual mode, you select text using movement keys before you decide what to do with it.": "In visual mode, you select text using movement keys before you decide what to do with it.",
      "Let's see how. Goto visual mode with |v|. Then select a word with |e|. After you've selected the text, you can delete it with |d|.": "Let's see how. Goto visual mode with |v|. Then select a word with |e|. After you've selected the text, you can delete it with |d|.",
      "This sentence has not seen the light.": "This sentence has not seen the light.",
      "Visual block mode, ctrl-v": "Visual block mode, ctrl-v",
      "There is yet another mode: |visual block|. This makes it possible to insert text on many lines at once. Let's see how with an example list.": "There is yet another mode: |visual block|. This makes it possible to insert text on many lines at once. Let's see how with an example list.",
      "<> A smart girl": "<> A smart girl",
      "<> Ulysses": "<> Ulysses",
      "<> Learn and teach": "<> Learn and teach",
      "First, move cursor to insert position. Then press |ctrl-v| to go into visual block mode. Move cursor vertically to select lines. Now press |I|, and prepend text to the selected area. |Esc| completes the insertion.": "First, move cursor to insert position. Then press |ctrl-v| to go into visual block mode. Move cursor vertically to select lines. Now press |I|, and prepend text to the selected area. |Esc| completes the insertion.",
      "Real Vim awaits": "Real Vim awaits",
      "Now you should be quite confident to enter the real Vim.": "Now you should be quite confident to enter the real Vim.",
      "Most important commands to remember are |:w| (save), |:q| (quit), and |:q!| (quit without saving).": "Most important commands to remember are |:w| (save), |:q| (quit), and |:q!| (quit without saving).",
      "Also don't |PANIC!| If you make a mistake, press |u| for undo and |ctrl+R| for redo": "Also don't |PANIC!| If you make a mistake, press |u| for undo and |ctrl+R| for redo",
      "If you have a problem, or want to learn more about what Vim offers, type |:help|": "If you have a problem, or want to learn more about what Vim offers, type |:help|",
      "The end": "The end",
      "Thank you for your time. I hope you enjoyed.": "Thank you for your time. I hope you enjoyed.",
      "Press |space| if you want to test out the commands freely in the practice editor.": "Press |space| if you want to test out the commands freely in the practice editor.",
      "Bye!": "Bye!"
  }
};
//获取浏览器本地语言
var locale = navigator.language || navigator.userLanguage;
// 当前本地化配置
var localizer = localizers[locale] || localizers['en'];
