let localizers = {
  
  'zh-CN': {
    "Introduction": "介绍",
    "Hello.": "你好。",
    "I am an interactive |Vim| tutorial.": "我是一个互动的 |Vim| 教程。",
    "I'll teach you what Vim is about without hassle. If you are in a hurry, press any key to fast forward.": "我将教你如何使用 Vim，简单易懂。如果你着急，按任意键快进。",
    "To practice what you've learned, try out the |practice| page. It has a context sensitive reference for commands.": "为了练习所学的内容，请尝试使用 |practice| 页面。它提供了命令的上下文敏感参考。",
    "Now, let me introduce you to basics of Vim.": "现在，让我向你介绍 Vim 的基础知识。",
    "Two modes, insert and normal": "Vim 有两种基本模式，插入模式和正常模式。",
    "Vim has two basic modes. One is |insert| mode, in which you write text as if in normal text editor.": "Vim 有两种基本模式。一种是 |插入| 模式，在这种模式下，你可以像在普通文本编辑器中一样输入文本。",
    "Another is |normal| mode which provides you efficient ways to navigate and manipulate text.": "另一种是 |正常| 模式，它为你提供了高效的文本导航和操作方式。",
    "At any time, you can see which mode you are in on the status bar which is located at the top of the editor.": "你可以随时在位于编辑器顶部的状态栏上看到你当前所处的模式。",
    "To change between modes, use |Esc| for normal mode and |i| for insert mode": "要在模式之间切换，请使用 |Esc| 进入正常模式，使用 |i| 进入插入模式",
    "Let's try it out! First, change to insert mode.": "让我们试一试！首先，切换到插入模式。",
    "Basic movement: h, j, k, and l": "基本移动：h、j、k 和 l",
    "In contrast to regular text editor, you use keys |h|, |j|, |k|, and |l| instead of arrow keys to move the cursor.": "与普通文本编辑器不同，你使用键盘上的 |h|、|j|、|k| 和 |l| 键来移动光标，而不是箭头键。",
    "Let's see how it works in practice!": "让我们看看它在实践中是如何工作的！",
    "Word movement: w, e, b": "单词移动：w、e、b",
    "To navigate the text in terms of words, you can use keys |w|, |b|, and |e| (also W, B, E in real Vim).": "要按单词导航文本，你可以使用键盘上的 |w|、|b| 和 |e|（在真实的 Vim 中也是如此）。",
    "|w| moves to the start of next word; |e| moves to the end of the word; and |b| moves to beginning of the word.": "|w| 移动到下一个单词的开头；|e| 移动到单词的末尾；|b| 移动到单词的开头。",
    "Number powered movement, e.g. 5w": "数字控制移动，例如 5w",
    "Moving within the text is not limited to individual keys; you can combine movement keys with a |number|. For example, |3w| is the same as pressing w three times.": "在文本中移动不仅限于单个键；你可以将移动键与 |数字| 结合使用。例如，|3w| 等同于连续按下 w 键三次。",
    "Insert text repeatedly, e.g. 3iYes": "重复插入文本，例如 3iYes",
    "You can insert text multiple times.": "你可以多次插入文本。",
    "For example, an underline of a header might consist of 30 |-|s.": "例如，标题的下划线可能由 30 个 |-| 组成。",
    "------------------------------": "------------------------------",
    "With |30i-| |Esc|, there's no need to press |-| 30 times.": "使用 |30i-| |Esc|，无需按下 |-| 键 30 次。",
    "Let's try it out: insert |go| three times.": "让我们试一试：插入 |go| 三次。",
    "Find a character, f and F": "查找字符，f 和 F",
    "To find and move to the next (or previous) occurrence of a character, use |f| and |F|, e.g. |fo| finds next o.": "要查找并移动到字符的下一个（或上一个）出现位置，请使用 |f| 和 |F|，例如 |fo| 查找下一个 o。",
    "You can combine f with a number. For example, you can find 3rd occurrence of 'q' with |3fq|, que?": "你可以将 f 与数字结合使用。例如，你可以使用 |3fq| 查找第三个 'q'，que?",
    "Go to matching parentheses, %": "跳转到匹配的括号，%",
    "In text that is structured with parentheses or brackets, |(| or |{| or |[|, use |%| to jump to the matching parenthesis or bracket.": "在由括号或方括号结构化的文本中，使用 |%| 跳转到匹配的括号或方括号。",
    "Here is (a sample) text to try that.": "这是一个（示例）文本，可以尝试一下。",
    "Go to start/end of line, 0 and $": "跳转到行首/行尾，0 和 $",
    "To reach the beginning of a line, press |0|.": "要到达行首，请按 |0|。",
    "For the end of a line, there's |$|": "要到达行尾，使用 |$|",
    "Find word under cursor, * and #": "查找光标下的单词，* 和 #",
    "Find the next occurrence of the word under cursor with |*|, and the previous with |#|.": "使用 |*| 查找光标下的下一个单词，使用 |#| 查找上一个单词。",
    "Goto line, g and G": "跳转到行，g 和 G",
    "|gg| takes you to the beginning of the file; |G| to the end.": "|gg| 跳转到文件开头；|G| 跳转到文件末尾。",
    "To jump directly to a specific line, give its |line number| along with |G|.": "要直接跳转到特定行，请在 |G| 后面加上行号。",
    "Now go to the beginning of this screen with |gg| and then back to end with |G|.": "现在使用 |gg| 跳转到屏幕开头，然后使用 |G| 返回到屏幕末尾。",
    "Search, /text with n and N": "搜索，/text，使用 n 和 N",
    "Searching text is a vital part of any text editor. In Vim, you press |/|, and give the text you are looking for.": "搜索文本是任何文本编辑器的重要部分。在 Vim 中，你按 |/|，然后输入你要搜索的文本。",
    "You can repeat the search for next and previous occurrences with |n| and |N|, respectively.": "你可以使用 |n| 和 |N| 分别重复搜索下一个和上一个出现的位置。",
    "For advanced use cases, it's possible to use regexps that help to find text of particular form (In real Vim).": "对于高级用例，可以使用正则表达式来查找特定形式的文本（在真实的 Vim 中）。",
    "Let's try a simple text search.": "让我们尝试一个简单的文本搜索。",
    "Search for |text| and find the subsequent matches with |n|.": "搜索 |text| 并使用 |n| 查找后续匹配项。",
    "Removing a character, x and X": "删除字符，x 和 X",
    "|x| and |X| delete the character under the cursor and to the left of the cursor, respectively": "|x| 和 |X| 分别删除光标下的字符和光标左侧的字符",
    "Try pressing |x| to remove the last word.": "尝试按下 |x| 删除最后一个单词。",
    "Replacing letter under cursor, r": "替换光标下的字母，r",
    "When you need to replace only one character under your cursor, without changing to insert mode, use |r|.": "当你只需要替换光标下的一个字符，而不切换到插入模式时，请使用 |r|。",
    "Replace my": "替换 my",
    "Insert new line, o and O": "插入新行，o 和 O",
    "To insert text into a new line, press |o| or |O|": "要在新行中插入文本，请按 |o| 或 |O|",
    "After new line is created, the editor is set to |insert| mode.": "创建新行后，编辑器将设置为 |插入| 模式。",
    "Write a bit and get back to |normal| mode.": "写一点内容，然后返回 |正常| 模式。",
    "Deleting, d": "删除，d",
    "|d| is the delete command": "|d| 是删除命令",
    "You can combine it with movement, e.g. |dw| deletes the first word on the right side of the cursor": "你可以将其与移动结合使用，例如 |dw| 删除光标右侧的第一个单词",
    "It also copies the content, so that you can paste it with |p| to another location (on real Vim).": "它还会复制内容，这样你就可以使用 |p| 将其粘贴到另一个位置（在真实的 Vim 中）。",
    "Repetition with .": "使用 . 进行重复",
    "To repeat the previous command, just press |.|": "要重复执行上一个命令，只需按下 |.|",
    "First, remove two words with |d2w|.": "首先，使用 |d2w| 删除两个单词。",
    "After that, remove the rest of the words in this line with |.|": "然后，使用 |.| 删除本行的其余单词。",
    "Visual mode, v": "可视模式，v",
    "Besides insert and normal mode, Vim has also |visual| mode.": "除了插入模式和正常模式，Vim 还有 |可视| 模式。",
    "In visual mode, you select text using movement keys before you decide what to do with it.": "在可视模式下，你可以使用移动键选择文本，然后再决定如何处理它。",
    "Let's see how. Goto visual mode with |v|. Then select a word with |e|. After you've selected the text, you can delete it with |d|.": "让我们看看如何操作。使用 |v| 进入可视模式。然后使用 |e| 选择一个单词。选择文本后，你可以使用 |d| 删除它。",
    "This sentence has not seen the light.": "这个句子还没有见过光。",
    "Visual block mode, ctrl-v": "可视块模式，ctrl-v",
    "There is yet another mode: |visual block|. This makes it possible to insert text on many lines at once. Let's see how with an example list.": "还有另一种模式：|可视块|。它可以一次在多行上插入文本。让我们通过一个示例列表来看看如何操作。",
    "<> A smart girl": "<> 一个聪明的女孩",
    "<> Ulysses": "<> 尤利西斯",
    "<> Learn and teach": "<> 学习和教学",
    "First, move cursor to insert position. Then press |ctrl-v| to go into visual block mode. Move cursor vertically to select lines. Now press |I|, and prepend text to the selected area. |Esc| completes the insertion.": "首先，将光标移动到插入位置。然后按下 |ctrl-v| 进入可视块模式。垂直移动光标以选择行。现在按下 |I|，在所选区域前插入文本。按 |Esc| 完成插入。",
    "Real Vim awaits": "真正的 Vim 等待着你",
    "Now you should be quite confident to enter the real Vim.": "现在你应该对进入真正的 Vim 感到非常自信。",
    "Most important commands to remember are |:w| (save), |:q| (quit), and |:q!| (quit without saving).": "最重要的命令是 |:w|（保存）、|:q|（退出）和 |:q!|（不保存退出）。",
    "Also don't |PANIC!| If you make a mistake, press |u| for undo and |ctrl+R| for redo": "此外，不要 |慌张！| 如果你犯了错误，按 |u| 进行撤销，按 |ctrl+R| 进行重做",
    "If you have a problem, or want to learn more about what Vim offers, type |:help|": "如果你有问题，或者想了解更多关于Vim的功能，输入 |:help|",
    "The end": "结束",
    "Thank you for your time. I hope you enjoyed.": "感谢你的时间，希望你喜欢。",
    "Press |space| if you want to test out the commands freely in the practice editor.": "如果你想在练习编辑器中自由测试命令，请按 |空格键|。",
    "Bye!": "再见！",
    "Good, now you're in insert mode. Write something and change back to normal mode.": "好的，现在你处于插入模式。写点什么，然后切换回正常模式。",
    "Good. Let's move on to another section.": "很好。让我们继续下一节。",
    "Let's move on.": "让我们继续。",
    "Word! Let's move on.": "词！我们继续。",
    "With numbers, ain't no numbness. ": "有了数字，就没有麻木感。",
    "F-f-f-ast!": "快！非常迅速！",
    "Nothing new under the cursor": "光标下没有新东西",
    "Go to line 2 with 2G.": "使用2G跳转到第2行。",
    "gg! G majorly rocks": "gg！G键真是太棒了。",
    "Slash through the needles with /n/e/e/d/l/e/s": "用/n/e/e/d/l/e/s穿越针眼。",
    "Sometimes the treasure is the indicator (x).": "有时宝藏就是指示器（x）。",
    "You removed yourself from this section. Next!": "你已经离开了这个部分。下一个！",
    "Yep! Now big O to insert a new line above the current line.": "是的！现在用大写O在当前行上方插入新行。",
    "I bet you feel like O___o": "我打赌你感觉像O___o。",
    "The word is gone. Now let's remove two words with d2e.": "这个单词没了。现在让我们用d2e删除两个单词。",
    "To 'de' or not to 'de', is not the question, anymore.": "'删除'还是'不删除'，这不再是问题。",
    "Repetition is the root of all periods": "重复是一切周期的根源"
  }
};
//获取浏览器本地语言
var locale = navigator.language || navigator.userLanguage;
// 当前本地化配置
var localizer = localizers[locale] || localizers['en'];
